mlp_hidden_size: [200]          # (list of int) The MLP hidden layer.
latent_dimension: 64           # (int) The latent dimension of auto-encoder.
dropout_prob: 0.7               # (float) The drop out probability of input.  
anneal_cap: 0.2                 # (float) The hyper parameter of the weight of KL loss. 
total_anneal_steps: 2000      # (int) The maximum steps of anneal update.
learning_rate: 1e-3
use_user_loader: true